#!/bin/bash
# Guard test: every *.sh under scripts/ and hooks/scripts/ must carry the git
# index mode its call sites require — 100755 if any call site invokes it as a
# direct path (./x, a hooks.json command, or a bare path passed to an
# interpreter binary), 100644 if every call site only `source`s it. This is an
# explicit expected-modes manifest, not a blanket "everything must be +x"
# check, because sourced-only libs must NOT be executable (PR #92's own audit
# established this for discipline_common.sh, config.sh, review-artifact.sh).
#
# To update legitimately: when a new *.sh file is added or a file's call
# sites change (a sourced-only lib becomes directly invoked, or vice versa),
# re-run the call-site audit (grep the repo for the filename) and edit its
# entry below to match the new reality — do not edit this file just to make
# a test pass without re-auditing.
#
# Uses parallel arrays, not `declare -A`, for bash 3.2 (macOS default) compat
# — same constraint the other *.test.sh files in this directory respect.
#
# Usage: bash exec_bit_invariant.test.sh
set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$REPO_ROOT" || exit 1

fails=0
check() { # path expected_mode actual_mode
  if [ "$2" = "$3" ]; then printf 'ok   - %s (%s)\n' "$1" "$2"
  else printf 'FAIL - %s (expected %s, got %s)\n' "$1" "$2" "$3"; fails=$((fails+1)); fi
}

# Parallel arrays: path -> expected mode (100644 = source-only, 100755 =
# invoked as a direct path somewhere in the repo).
manifest_paths=(
  scripts/lib/git-common.sh
  scripts/lib/config.sh
  scripts/lib/review-artifact.sh
  scripts/lib/eval-artifact.sh
  hooks/scripts/lib/agentic_loop_path.sh
  hooks/scripts/lib/discipline_common.sh
  hooks/scripts/lib/loop_cost.sh
  hooks/scripts/lib/loop_state_common.sh
  scripts/sandbox/render-settings.sh
  scripts/sandbox/spawn-sandboxed-worker.sh
  scripts/sandbox/sandbox-probe.sh
  scripts/merge.sh
  scripts/post_review.sh
  scripts/post_evals.sh
  scripts/push.sh
  hooks/scripts/check_confidence_labels.sh
  hooks/scripts/check_verify_loop.sh
  hooks/scripts/comment_citation_gate.sh
  hooks/scripts/crack_on_gate.sh
  hooks/scripts/crack_on_prose_gate.sh
  hooks/scripts/destructive_bash_gate.sh
  hooks/scripts/enforce_pr_workflow.sh
  hooks/scripts/inject_bootstrap.sh
  hooks/scripts/inject_context.sh
  hooks/scripts/loop_stall_guard.sh
  hooks/scripts/loop_state_guard.sh
  hooks/scripts/no_edit_on_main.sh
  hooks/scripts/offload_push_guard.sh
  hooks/scripts/test_gate.sh
  hooks/scripts/unregistered_loop_guard.sh
  hooks/scripts/voice_announce.sh
  skills/dashboard/runner/bin/sweeper.sh
  skills/dashboard/runner/bin/seed-and-sweep.sh
  launchd/install-routines.sh
  launchd/uninstall-routines.sh
)
manifest_modes=(
  100644
  100644
  100644
  100644
  100644
  100644
  100644
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
  100755
)

# 1. Every path in the manifest must exist and match its expected mode.
i=0
while [ "$i" -lt "${#manifest_paths[@]}" ]; do
  path="${manifest_paths[$i]}"
  expected_mode="${manifest_modes[$i]}"
  actual=$(git ls-files -s -- "$path" | awk '{print $1}')
  if [ -z "$actual" ]; then
    printf 'FAIL - %s is in the manifest but not tracked by git\n' "$path"
    fails=$((fails+1))
  else
    check "$path" "$expected_mode" "$actual"
  fi
  i=$((i+1))
done

# 2. Every *.sh under scripts/ and hooks/scripts/ (excluding tests/, which
#    normalise to 755 for peer consistency per PR #92 and aren't part of this
#    invariant) must appear in the manifest — catches new files silently
#    drifting from either bucket.
is_in_manifest() {
  local target="$1" p
  for p in "${manifest_paths[@]}"; do
    [ "$p" = "$target" ] && return 0
  done
  return 1
}

while IFS= read -r path; do
  [ -z "$path" ] && continue
  if ! is_in_manifest "$path"; then
    printf 'FAIL - %s is tracked under scripts/ or hooks/scripts/ but missing from the manifest — add it after auditing its call sites\n' "$path"
    fails=$((fails+1))
  fi
done < <(git ls-files 'scripts/*.sh' 'hooks/scripts/*.sh' 'hooks/scripts/lib/*.sh' | grep -v '/tests/')

[ "$fails" -eq 0 ] && { echo "PASS"; exit 0; } || { echo "FAILED ($fails)"; exit 1; }
