#!/usr/bin/env python3
"""Optional typed-memory adapter over the `muninn` CLI (subprocess only; muninn needs py3.12, Coderails is py3.9).

Every failure returns a `Degraded(reason)` value instead of raising, so callers fall back to the Markdown memory path.
Reason codes: muninn_absent, muninn_old_ledger, muninn_timeout, muninn_error, uncited_write, restricted_refused,
bad_record, handwritten_protected. Each one appends a fail-open trace row (command `memory.<op>`).
"""

from __future__ import annotations

import argparse
import contextlib
import dataclasses
import json
import os
import re
import runpy
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, cast

TIMEOUT = 10.0
MARKER = "<!-- generated by memory_adapter -->"
SCOPES = ("user", "project", "repository", "loop")
TYPES = ("fact", "decision", "preference", "constraint", "lesson")
CONFIDENCE = ("observed", "reported", "inferred")
ADD_FLAGS = (
    "--scope-loop",
    "--confidence",
    "--valid-until",
    "--sensitivity",
    "--contradicts",
    "--tag",
    "lesson",
    "constraint",
)
TAG = re.compile(r"[a-z0-9_-]{1,32}")  # muninn's own tag rule
DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
PROBE_CACHE: dict[str, str | None] = {}


@dataclasses.dataclass
class Degraded:
    """A refusal or degrade; `reason` is a low-cardinality code."""

    reason: str


@dataclasses.dataclass
class Record:
    """One typed memory record; id/created_at are filled from muninn on read."""

    scope: str
    type: str
    claim: str
    cite: str
    quote: str
    tags: list[str] = dataclasses.field(default_factory=list[str])
    loop_id: str | None = None
    confidence: str | None = None
    valid_until: str | None = None
    supersedes: str | None = None
    contradicts: str | None = None
    sensitivity: str = "normal"
    id: str | None = None
    created_at: str | None = None


def validate(r: Record) -> str | None:
    """Return a reason code when the record may not be written, else None."""
    if not r.cite.strip() or not r.quote.strip():
        return "uncited_write"
    if r.sensitivity == "restricted":
        return "restricted_refused"
    ok = (
        r.scope in SCOPES
        and r.type in TYPES
        and bool(r.claim.strip())
        and r.sensitivity == "normal"
        and (r.confidence is None or r.confidence in CONFIDENCE)
        and (r.valid_until is None or DATE.fullmatch(r.valid_until) is not None)
        and all(TAG.fullmatch(t) for t in r.tags)
        and (r.scope != "loop" or bool(r.loop_id))
    )
    return None if ok else "bad_record"


def _trace(op: str, reason: str, session_id: str, loop_id: str | None) -> None:
    """Append a fail-open trace row via hooks/scripts/lib/trace_row.py when this layout ships it."""
    try:
        path = Path(__file__).resolve().parents[2] / "hooks/scripts/lib/trace_row.py"
        runpy.run_path(str(path))["append_row"](f"memory.{op}", "degraded", reason, session_id, loop_id)
    except Exception:  # fail open: tracing never blocks memory
        return


def _run(args: list[str]) -> str | Degraded:
    exe = shutil.which("muninn")
    if exe is None:
        return Degraded("muninn_absent")
    try:
        p = subprocess.run([exe, *args], capture_output=True, text=True, timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        return Degraded("muninn_timeout")
    except OSError:
        return Degraded("muninn_error")
    return p.stdout if p.returncode == 0 else Degraded("muninn_error")


def probe() -> Degraded | None:
    """Check once per process that `muninn know add|list --help` advertises every Part A flag."""
    key = shutil.which("muninn") or ""
    if key not in PROBE_CACHE:
        add_help, list_help = _run(["know", "add", "--help"]), _run(["know", "list", "--help"])
        if isinstance(add_help, Degraded):
            PROBE_CACHE[key] = add_help.reason
        elif isinstance(list_help, Degraded):
            PROBE_CACHE[key] = list_help.reason
        elif any(f not in add_help for f in ADD_FLAGS) or "--scope-loop" not in list_help:
            PROBE_CACHE[key] = "muninn_old_ledger"
        else:
            PROBE_CACHE[key] = None
    reason = PROBE_CACHE[key]
    return Degraded(reason) if reason else None


def _fail(op: str, reason: str, session_id: str, loop_id: str | None = None) -> Degraded:
    _trace(op, reason, session_id, loop_id)
    return Degraded(reason)


def add(r: Record, session_id: str = "") -> Degraded | None:
    """Write one cited record via `muninn know add`; None on success."""
    bad = validate(r)
    if bad:
        return _fail("add", bad, session_id, r.loop_id)
    down = probe()
    if down:
        return _fail("add", down.reason, session_id, r.loop_id)
    argv = ["know", "add", "--kind", r.type, "--text", r.claim, "--cite", r.cite, "--quote", r.quote]
    argv += ["--sensitivity", r.sensitivity]
    argv += ["--scope-loop", r.loop_id or ""] if r.scope == "loop" else ["--global"] if r.scope == "user" else []
    for flag, val in (
        ("--confidence", r.confidence),
        ("--valid-until", r.valid_until),
        ("--supersedes", r.supersedes),
        ("--contradicts", r.contradicts),
    ):
        if val:
            argv += [flag, val]
    for t in r.tags:
        argv += ["--tag", t]
    out = _run(argv)
    return _fail("add", out.reason, session_id, r.loop_id) if isinstance(out, Degraded) else None


def list_records(
    scope: str,
    loop_id: str | None = None,
    type: str | None = None,
    tags: list[str] | None = None,
    query: str | None = None,
    session_id: str = "",
) -> list[Record] | Degraded:
    """Return current, non-expired, non-restricted records with provenance (id, cite, quote)."""
    down = probe()
    if down:
        return _fail("list", down.reason, session_id, loop_id)
    argv = ["know", "list", "--status", "current"]
    argv += ["--kind", type] if type else []
    argv += ["--scope-loop", loop_id] if scope == "loop" and loop_id else []
    out = _run(argv)
    if isinstance(out, Degraded):
        return _fail("list", out.reason, session_id, loop_id)
    try:
        entries: list[dict[str, Any]] = json.loads(out)["entries"]
        found: list[Record] = []
        for e in entries:
            if e.get("sensitivity") == "restricted" or e.get("expired"):
                continue
            if tags and not set(tags) <= set(e.get("tags") or []):
                continue
            if query and query.lower() not in e["text"].lower():
                continue
            cite = cast("dict[str, str]", (e.get("cites") or [{}])[0])
            found.append(
                Record(
                    scope=scope,
                    type=e["kind"],
                    claim=e["text"],
                    cite=cite.get("ref", ""),
                    quote=cite.get("quote", ""),
                    tags=list(e.get("tags") or []),
                    loop_id=loop_id,
                    confidence=e.get("confidence"),
                    valid_until=e.get("valid_until"),
                    id=e["id"],
                    created_at=e.get("date"),
                )
            )
        return found
    except (ValueError, KeyError, TypeError, AttributeError):
        return _fail("list", "muninn_error", session_id, loop_id)


def render(records: list[Record], title: str = "Memory Index") -> str:
    """Render records as a marker-stamped Markdown view."""
    lines = [MARKER, f"# {title}", ""]
    lines += [f"- [{r.id}] ({r.type}) {' '.join(r.claim.split())} -- cite `{r.cite}`" for r in records]
    return "\n".join(lines) + "\n"


def write_view(path: Path, text: str, session_id: str = "") -> Degraded | None:
    """Atomically write a generated view, only over an absent or marker-stamped file."""
    path = Path(path)
    if path.exists():
        try:
            first = path.read_text(encoding="utf-8").split("\n", 1)[0]
        except OSError:
            return _fail("render", "muninn_error", session_id)
        if first != MARKER:
            return _fail("render", "handwritten_protected", session_id)
    tmp = None
    try:
        fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".tmp")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
        return None
    except OSError:
        if tmp:
            with contextlib.suppress(OSError):
                os.unlink(tmp)
        return _fail("render", "muninn_error", session_id)


def main(argv: list[str] | None = None) -> int:
    """CLI: add|list|render|probe. Exit 0 ok, 3 degraded (reason on stdout as JSON)."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("cmd", choices=("add", "list", "render", "probe"))
    ap.add_argument("--type")
    ap.add_argument("--scope", default="loop", choices=SCOPES)
    ap.add_argument("--loop")
    ap.add_argument("--run", help="adds tag run-<id[:28]>")
    ap.add_argument("--claim")
    ap.add_argument("--cite", default="")
    ap.add_argument("--quote", default="")
    ap.add_argument("--confidence")
    ap.add_argument("--valid-until")
    ap.add_argument("--supersedes")
    ap.add_argument("--contradicts")
    ap.add_argument("--tag", action="append", default=[])
    ap.add_argument("--query")
    ap.add_argument("--session", default=os.environ.get("CLAUDE_SESSION_ID", ""))
    ap.add_argument("--memory-md", action="store_true")
    ap.add_argument("--standing-orders", action="store_true")
    ap.add_argument("--write", metavar="PATH")
    a = ap.parse_args(argv)
    tags: list[str] = a.tag + ([f"run-{a.run[:28].lower()}"] if a.run else [])
    res: Degraded | None = None
    if a.cmd == "probe":
        res = probe()
    elif a.cmd == "add":
        rec = Record(a.scope, a.type or "", a.claim or "", a.cite, a.quote, tags, a.loop)
        rec.confidence, rec.valid_until, rec.supersedes, rec.contradicts = (
            a.confidence,
            a.valid_until,
            a.supersedes,
            a.contradicts,
        )
        res = add(rec, a.session)
    else:
        found = list_records(a.scope, a.loop, "lesson" if a.standing_orders else a.type, tags, a.query, a.session)
        if isinstance(found, Degraded):
            res = found
        elif a.cmd == "list":
            print(json.dumps([dataclasses.asdict(r) for r in found], indent=2))
        else:
            text = render(found, "Standing Orders" if a.standing_orders else "Memory Index")
            if a.write:
                res = write_view(Path(a.write), text, a.session)
            else:
                sys.stdout.write(text)  # dry-run by default
    if res is not None:
        print(json.dumps({"degraded": res.reason}))
        return 3
    if a.cmd in ("add", "probe"):
        print(json.dumps({"ok": True}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
