#!/usr/bin/env python3
"""Generate docs/closure-matrix.md from docs/closure-matrix.json; validate the data.

Usage: closure_matrix.py [--check]   (no flag rewrites the md; --check exits 1 if stale or invalid)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs/closure-matrix.json"
MD = ROOT / "docs/closure-matrix.md"
ROW_IDS = [str(n) for n in range(1, 24)] + ["5a"]
GAP_IDS = [f"gap{n}" for n in range(1, 6)]

HEADER = """# Phase 0 closure matrix

<!-- GENERATED by scripts/closure_matrix.py from docs/closure-matrix.json. Do not edit; run the script. -->

**What "closed" means** (plan section 2). A row or gap is closed only when all of these hold:

1. Built and merged.
2. An enforcing caller exists and is ON by default.
3. A both-provider (Claude and Codex) proof exists, with a negative control.
4. Installed live.
5. Reason codes, trace, runbook entry and measurement exist.
6. Limits are documented.

The integrity gate (gap1) stays opt-in. It is the documented exception, closed by
[`INTEGRITY-GATE.md`](INTEGRITY-GATE.md), is not installed here, and gets no second enforcement route.

Phase 0 and Phase 7 are cross-cutting. Phase 7 is the live cutover and closure acceptance for every row.
"""


def validate(data: dict[str, Any]) -> list[str]:
    """Return a list of problems; empty means the data is complete."""
    errs: list[str] = []
    rows = {r.get("id"): r for r in data.get("rows", [])}
    gaps = {g.get("id"): g for g in data.get("gaps", [])}
    for i in ROW_IDS:
        r = rows.get(i)
        if r is None:
            errs.append(f"row {i} missing")
            continue
        if not isinstance(r.get("phase"), int) or not 1 <= r["phase"] <= 6:
            errs.append(f"row {i} has no phase 1-6")
        if not str(r.get("acceptance_test", "")).strip():
            errs.append(f"row {i} has empty acceptance_test")
    for i in GAP_IDS:
        g = gaps.get(i)
        if g is None:
            errs.append(f"{i} missing")
            continue
        if not str(g.get("acceptance_test", "")).strip():
            errs.append(f"{i} has empty acceptance_test")
        if i == "gap1":
            if not str(g.get("exception", "")).strip():
                errs.append("gap1 has no exception (opt-in integrity gate)")
        elif not isinstance(g.get("phase"), int):
            errs.append(f"{i} is unmapped (no phase)")
    return errs


def _cell(v: object) -> str:
    return str(v).replace("|", "\\|").replace("\n", " ")


def render(data: dict[str, Any]) -> str:
    """Render the data as the generated markdown document."""
    out = [HEADER, "## Inventory rows\n"]
    out.append("| id | phase | defect | target record | source refs | acceptance test | status |")
    out.append("|---|---|---|---|---|---|---|")
    for r in data["rows"]:
        cols = [r["id"], r["phase"], r["defect"], r["target_typed_record"], r["source_refs"]]
        cols += [r["acceptance_test"], r["status"]]
        out.append("| " + " | ".join(_cell(c) for c in cols) + " |")
    out.append("\n## Gaps\n")
    out.append("| id | gap | phase or exception | acceptance test | status |")
    out.append("|---|---|---|---|---|")
    for g in data["gaps"]:
        where = g.get("exception") or f"Phase {g['phase']}"
        cols = [g["id"], g["title"], where, g["acceptance_test"], g["status"]]
        out.append("| " + " | ".join(_cell(c) for c in cols) + " |")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    """Validate, then write the md or (with --check) compare it."""
    data = json.loads(DATA.read_text())
    errs = validate(data)
    if errs:
        print("\n".join(errs), file=sys.stderr)
        return 1
    text = render(data)
    if "--check" in argv:
        if not MD.exists() or MD.read_text() != text:
            print("docs/closure-matrix.md is stale; run scripts/closure_matrix.py", file=sys.stderr)
            return 1
        return 0
    MD.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
