#!/usr/bin/env python3
"""Generate docs/closure-matrix.md from docs/closure-matrix.json; validate the data.

Usage: closure_matrix.py [--check]   (no flag rewrites the md; --check exits 1 if stale or invalid)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs/closure-matrix.json"
MD = ROOT / "docs/closure-matrix.md"
ROW_IDS = [str(n) for n in range(1, 24)] + ["5a"]
GAP_IDS = [f"gap{n}" for n in range(1, 6)]

HEADER = """# Phase 0 closure matrix

<!-- GENERATED by scripts/closure_matrix.py from docs/closure-matrix.json. Do not edit; run the script. -->

**What "closed" means** (plan section 2). A row or gap is closed only when all of these hold:

1. Built and merged.
2. An enforcing caller exists and is ON by default.
3. A both-provider (Claude and Codex) proof exists, with a negative control.
4. Installed live.
5. Reason codes, trace, runbook entry and measurement exist.
6. Limits are documented.

The integrity gate (gap1) stays opt-in. It is the documented exception, closed by
[`INTEGRITY-GATE.md`](INTEGRITY-GATE.md), is not installed here, and gets no second enforcement route.

Phase 0 and Phase 7 are cross-cutting. Phase 7 is the live cutover and closure acceptance for every row.
"""


ROW_STR = ("defect", "target_typed_record", "source_refs", "acceptance_test", "status")
GAP_STR = ("title", "acceptance_test", "status")
# Plan section 5 phase map; the validator fails a row or gap moved to another phase.
PHASES = {1: "6 10 16 19", 2: "1 4 5 5a 7 22", 3: "2 3", 4: "8 9 17 18 20 21", 5: "13 14 15", 6: "11 12 23"}
ROW_PHASE = {i: p for p, ids in PHASES.items() for i in ids.split()}
GAP_PHASE = {"gap2": 3, "gap3": 3, "gap4": 6, "gap5": 5}


def _blank(v: object) -> bool:
    return not (isinstance(v, str) and v.strip())


def _phase_ok(v: object) -> bool:
    return type(v) is int and 1 <= v <= 6


def _check_ids(
    kind: str, items: list[dict[str, Any] | str], expected: list[str], errs: list[str]
) -> dict[str, dict[str, Any]]:
    """Collect dict items by id, flagging non-dicts, duplicates and unexpected ids."""
    by_id: dict[str, dict[str, Any]] = {}
    for it in items:
        if not isinstance(it, dict):
            errs.append(f"{kind} entry is not an object")
            continue
        i = it.get("id")
        if i in by_id:
            errs.append(f"{kind} {i} duplicated")
        elif i not in expected:
            errs.append(f"{kind} {i!r} unexpected")
        else:
            by_id[i] = it
    return by_id


def validate(data: dict[str, Any]) -> list[str]:
    """Return a list of problems; empty means the data is complete."""
    errs: list[str] = []
    rows = _check_ids("row", data.get("rows") or [], ROW_IDS, errs)
    gaps = _check_ids("gap", data.get("gaps") or [], GAP_IDS, errs)
    for i in ROW_IDS:
        r = rows.get(i)
        if r is None:
            errs.append(f"row {i} missing")
            continue
        if not _phase_ok(r.get("phase")):
            errs.append(f"row {i} has no phase 1-6")
        elif r["phase"] != ROW_PHASE[i]:
            errs.append(f"row {i} is in phase {r['phase']}, plan says {ROW_PHASE[i]}")
        if "blocked_on" in r and _blank(r["blocked_on"]):
            errs.append(f"row {i} has empty blocked_on")
        for k in ROW_STR:
            if _blank(r.get(k)):
                errs.append(f"row {i} has empty {k}")
    for i in GAP_IDS:
        g = gaps.get(i)
        if g is None:
            errs.append(f"{i} missing")
            continue
        for k in GAP_STR:
            if _blank(g.get(k)):
                errs.append(f"{i} has empty {k}")
        if i == "gap1":
            ex = str(g.get("exception"))
            if _blank(g.get("exception")) or "opt-in" not in ex or "INTEGRITY-GATE" not in ex:
                errs.append("gap1 has no exception (opt-in integrity gate)")
        elif not _phase_ok(g.get("phase")):
            errs.append(f"{i} is unmapped (no phase 1-6)")
        elif g["phase"] != GAP_PHASE[i]:
            errs.append(f"{i} is in phase {g['phase']}, plan says {GAP_PHASE[i]}")
    return errs


def _cell(v: object) -> str:
    return str(v).replace("|", "\\|").replace("\n", " ")


def render(data: dict[str, Any]) -> str:
    """Render the data as the generated markdown document."""
    out = [HEADER, "## Inventory rows\n"]
    out.append("| id | phase | defect | target record | source refs | acceptance test | blocked on | status |")
    out.append("|---|---|---|---|---|---|---|---|")
    for r in data["rows"]:
        cols = [r["id"], r["phase"], r["defect"], r["target_typed_record"], r["source_refs"]]
        cols += [r["acceptance_test"], r.get("blocked_on", ""), r["status"]]
        out.append("| " + " | ".join(_cell(c) for c in cols) + " |")
    out.append("\n## Gaps\n")
    out.append("| id | gap | phase or exception | acceptance test | status |")
    out.append("|---|---|---|---|---|")
    for g in data["gaps"]:
        where = g.get("exception") or f"Phase {g['phase']}"
        cols = [g["id"], g["title"], where, g["acceptance_test"], g["status"]]
        out.append("| " + " | ".join(_cell(c) for c in cols) + " |")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    """Validate, then write the md or (with --check) compare it."""
    data = json.loads(DATA.read_text())
    errs = validate(data)
    if errs:
        print("\n".join(errs), file=sys.stderr)
        return 1
    text = render(data)
    if "--check" in argv:
        if not MD.exists() or MD.read_text() != text:
            print("docs/closure-matrix.md is stale; run scripts/closure_matrix.py", file=sys.stderr)
            return 1
        return 0
    MD.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
